/* نصوصُ الواجهة بالألمانيّة. المفتاحُ هو النصُّ العربيُّ نفسُه كما في
   app.js و`ui-en.js`، فلا يُخترَع مفتاحٌ ثالثٌ يُنسى تحديثُه.

   وسلسلةُ الرجوع في `ui()`: الألمانيّةُ ← الإنجليزيّةُ ← العربيّة. فما
   ليس هنا يظهر بالإنجليزيّة، وما ليس في الاثنين يظهر بالعربيّة —
   ويكشف الناقصَ `tests/test_oberflaeche.py` فلا يبقى صامتاً.

   ملاحظةٌ لمن يعدّل: بعضُ المفاتيح شذراتُ HTML. إن غيّرتَ الوسمَ في
   app.js فغيّره هنا أيضاً، وإلّا سقط المفتاحُ وظهر السطرُ بلغةٍ أخرى. */
window.UI_DE = {
 " · آخر محاولة: ": " · letzter Versuch: ",
 " · أصبتَ ": " · richtig ",
 " · اجتزتَ الاختبار": " · bestanden",
 " · الأسئلة ": " · Fragen ",
 " · التوقيع: ": " · Unterschrift: ",
 " · الزمن: ": " · Zeit: ",
 " · المحور: ": " · Schwerpunkt: ",
 " · بنكُ الأسئلة ": " · Fragenpool ",
 " · تحت كلِّ خطوةٍ في غير موضعها سببُ موضعها.": " · Unter jedem Schritt, der falsch steht, steht der Grund für seinen Platz.",
 " · تحت كلِّ فراغٍ معناه وأساليبُه.": " · Unter jeder Lücke stehen die Bedeutung und die drei Register.",
 " · حكمُك: ": " · Ihr Urteil: ",
 " · دون حدّ النجاح (": " · unter der Bestehensgrenze (",
 " · سؤالُ «اختر كلَّ ما ينطبق» لا يُحتسب إلّا كاملاً": " · eine „Alles Zutreffende“-Frage zählt nur vollständig",
 " · عرفتُ ": " · gewusst ",
 " · قارنها بالأولى بأذنك": " · vergleichen Sie ihn nach Gehör mit dem ersten",
 " · لم أعرف ": " · nicht gewusst ",
 " · محاولات: ": " · Versuche: ",
 " · من ": " · aus ",
 " · وهذا مؤشّرُ بدءٍ لا تقييمٌ رسميّ": " · eine Orientierung, keine offizielle Bewertung",
 " · يثبت ": " · belegt ",
 " · يختبر ": " · prüft ",
 " · يعود ": " · kommt wieder ",
 " أسئلة · النجاح من ": " Fragen · Bestehensgrenze ",
 " أسئلة، دقيقةٌ لكلٍّ منها</li></ol>": " Fragen, je eine Minute</li></ol>",
 " أسئلة، فقد تتكرّر أسئلتُه بعد محاولاتٍ قليلة.": " Fragen, seine Fragen können sich also nach wenigen Versuchen wiederholen.",
 " أقسام · ": " Abschnitte · ",
 " بطاقة · المستحقُّ اليوم ": " Karten · heute fällig ",
 " بطاقة، فارتفعت صندوقاً.</li>": " Karten, die eine Box höher gerückt sind.</li>",
 " بلا تغطية": " ohne Abdeckung",
 " بنداً": " Posten",
 " بنداً في المراجعة · ": " Posten in der Wiederholung · ",
 " ث</td>": " s</td>",
 " ثانية · حالةُ النصّ: ": " Sekunden · Textstand: ",
 " ثمّ قارن التسجيلين.": " und vergleichen Sie dann die beiden Aufnahmen.",
 " دقيقة": " Minuten",
 " دقيقة</li>": " Minuten</li>",
 " دقيقة</p>": " Minuten</p>",
 " سؤالاً، تُختار منها اثنا عشر. ": " Fragen, aus denen zwölf gezogen werden. ",
 " صحيحة": " richtig",
 " غير مغطّى · ": " nicht abgedeckt · ",
 " في موضعها": " an der richtigen Stelle",
 " متطلّباً بلا تغطية.": " Anforderungen ohne Abdeckung.",
 " متطلّباً رسميّاً. <strong>كلُّ متطلَّبٍ في وحدةٍ واحدةٍ</strong> لا أكثرَ ": " offizielle Anforderungen. <strong>Jede Anforderung liegt in genau einer Einheit</strong>, nicht mehr ",
 " متطلّباً: ": " Anforderungen: ",
 " متطلّباً</div>": " Anforderungen</div>",
 " متطلّباً</p>": " Anforderungen</p>",
 " محاولة · أقررتَ بـ": " Versuche · bestätigt haben Sie ",
 " مرتبط · ": " belegt · ",
 " مرّات": " Mal",
 " مستحقٌّ اليوم": " heute fällig",
 " مستحقٌّ اليوم من ": " heute fällig von ",
 " مشهداً · ": " Szenen · ",
 " معتمد</div></td>": " freigegeben</div></td>",
 " مفردة) ←</a></p>": " Begriffe) →</a></p>",
 " من ": " von ",
 " من الأسئلة المكتوبة": " der schriftlichen Fragen",
 " وحدةً تقتسم ": " Einheiten teilen sich ",
 " — الترتيبُ كلُّه صحيح.": " — die ganze Reihenfolge stimmt.",
 " — مجموعُ أزمنة المحطّات المكتوبة في المحتوى": " — die Summe der im Inhalt festgehaltenen Stationszeiten",
 " — وما بقي فيه موضعُ مراجعةٍ فوقَه.": " — und was offen blieb, hat seinen Übungsort darüber.",
 "\">عُد إلى آخر موضع</a>": "\">Zurück zur letzten Stelle</a>",
 "\">كلُّ البطاقات</a></p>": "\">Alle Karten</a></p>",
 ") فيه ": ") enthält ",
 ".md</code> — مولَّدٌ بـ <code>tools/drehbuch.py</code></p>": ".md</code> — erzeugt mit <code>tools/drehbuch.py</code></p>",
 "</b> — انتهت الجلسة.": "</b> — Sitzung beendet.",
 "</b><span>جديدة</span></div>": "</b><span>neu</span></div>",
 "</b><span>صندوق ": "</b><span>Box ",
 "</b><span>غير مغطّى</span></div>": "</b><span>ohne Abdeckung</span></div>",
 "</b><span>مرتبط بأدلّة</span></div>": "</b><span>belegt</span></div>",
 "</b><span>معتمد سريريّاً ومنهجيّاً</span></div>": "</b><span>klinisch und curricular freigegeben</span></div>",
 "<a href=\"#/karten-intern\">بطاقات المعاينة الداخليّة</a>.</span></div>": "<a href=\"#/karten-intern\">die Karten der internen Vorschau</a>.</span></div>",
 "<b>تسجيلُك يبقى في متصفّحك</b>: لا يُرفع ولا يُحفَظ، ويزول بإغلاق الصفحة.</p>": "<b>Ihre Aufnahme bleibt in Ihrem Browser</b>: nichts wird hochgeladen, nichts gespeichert, und sie verschwindet, wenn Sie die Seite schließen.</p>",
 "<b>حكمُك أنت</b> — لا تصحيحَ آليّاً لها.</p><ul class=\"pr-selbst\">": "<b>Ihr eigenes Urteil</b> — hierfür gibt es keine automatische Bewertung.</p><ul class=\"pr-selbst\">",
 "<b>في التوثيق</b><span>": "<b>in der Dokumentation</b><span>",
 "<b>مع الفريق</b><span>": "<b>im Team</b><span>",
 "<b>مع المريض</b><span>": "<b>mit dem Patienten</b><span>",
 "<b>والقائمةُ فوقَه فيها الجواب</b> — أخفِها وجرّب من ذاكرتك.</p>": "<b>Und die Liste darüber enthält die Antwort</b> — blenden Sie sie aus und versuchen Sie es aus dem Gedächtnis.</p>",
 "<button class=\"haupt\" id=\"k-gut\">عرفتها</button>": "<button class=\"haupt\" id=\"k-gut\">Gewusst</button>",
 "<button class=\"haupt\" id=\"k-zeigen\">أظهر الجواب</button>": "<button class=\"haupt\" id=\"k-zeigen\">Antwort zeigen</button>",
 "<button class=\"haupt\" id=\"quiz-pruefen\">صحّح إجاباتي</button>": "<button class=\"haupt\" id=\"quiz-pruefen\">Antworten prüfen</button>",
 "<button class=\"s-ab\" disabled>🔁 النموذج ثمّ أنت</button>": "<button class=\"s-ab\" disabled>🔁 Modell, dann Sie</button>",
 "<button class=\"s-meins\" disabled>▶ تسجيلي</button>": "<button class=\"s-meins\" disabled>▶ meine Aufnahme</button>",
 "<button class=\"s-mik\">🎙 تكلّم أنت</button>": "<button class=\"s-mik\">🎙 Sie sprechen</button>",
 "<button class=\"s-modell\">▶ النموذج</button>": "<button class=\"s-modell\">▶ das Modell</button>",
 "<button class=\"s-nochmal\">أعد المحاولة</button>": "<button class=\"s-nochmal\">Noch einmal</button>",
 "<button id=\"auf-start\">ابدأ التسجيل</button>": "<button id=\"auf-start\">Aufnahme starten</button>",
 "<button id=\"auf-stop\" disabled>أوقف</button>": "<button id=\"auf-stop\" disabled>Stopp</button>",
 "<button id=\"k-schlecht\">لم أعرفها</button>": "<button id=\"k-schlecht\">Nicht gewusst</button>",
 "<button id=\"quiz-neu\">أعد المحاولة</button></div></div>": "<button id=\"quiz-neu\">Noch einmal</button></div></div>",
 "<details><summary>الإجابةُ النموذجيّة لهذه المحطّة</summary><ol>": "<details><summary>Die Musterantwort dieser Station</summary><ol>",
 "<details><summary>الإجابةُ النموذجيّة — مركّبةٌ من هذه الحالة</summary>": "<details><summary>Die Musterantwort — aus diesem Fall zusammengesetzt</summary>",
 "<details><summary>نصّ الفيديو — الألمانيّة متّصلة</summary><div>": "<details><summary>Videotext — durchgehend Deutsch</summary><div>",
 "<div class=\"band gut\">كلُّ المتطلّبات معتمدةٌ سريريّاً ومنهجيّاً.</div>": "<div class=\"band gut\">Alle Anforderungen sind klinisch und curricular freigegeben.</div>",
 "<div class=\"band gut\">لا بطاقةَ مستحقّةً اليوم.": "<div class=\"band gut\">Heute ist keine Karte fällig.",
 "<div class=\"band rot\">app/daten.js غائب — شغّل <code>python3 tools/bau.py</code>.</div>": "<div class=\"band rot\">app/daten.js fehlt — führen Sie <code>python3 tools/bau.py</code> aus.</div>",
 "<div class=\"band rot\">المنهج غير مكتمل — ": "<div class=\"band rot\">Das Curriculum ist unvollständig — ",
 "<div class=\"band rot\">خطّةُ المنهج غائبة — شغّل tools/bau.py.</div>": "<div class=\"band rot\">Der Curriculumsplan fehlt — führen Sie tools/bau.py aus.</div>",
 "<div class=\"band rot\">لا أسئلةَ موسومةً بمتطلَّب — ": "<div class=\"band rot\">Keine Frage trägt eine Anforderungsmarke — ",
 "<div class=\"band rot\">لا صفحةَ بهذا العنوان.</div>": "<div class=\"band rot\">Unter dieser Adresse gibt es keine Seite.</div>",
 "<div class=\"band rot\">لا عنصرَ بالمعرّف ": "<div class=\"band rot\">Kein Element mit der Kennung ",
 "<div class=\"band rot\">لا محطّاتِ تدريبٍ كافية لبناء جولة.</div>": "<div class=\"band rot\">Nicht genug Trainingsstationen für eine Runde.</div>",
 "<div class=\"band warn\">انتهى الوقتُ": "<div class=\"band warn\">Die Zeit ist um",
 "<div class=\"band warn\">بطاقاتُ المعاينة الداخليّة": "<div class=\"band warn\">Karten der internen Vorschau",
 "<div class=\"band warn\">تقييمٌ تدريبيٌّ لا رسميّ": "<div class=\"band warn\">Eine Übungsbewertung, keine offizielle",
 "<div class=\"band warn\">جوانبُ تحتاج محتوًى من مختصّ": "<div class=\"band warn\">Aspekte, die Inhalt von einer Fachperson brauchen",
 "<div class=\"band warn\">عند الرفض<span class=\"klein\">": "<div class=\"band warn\">Bei Ablehnung<span class=\"klein\">",
 "<div class=\"band warn\">قائمةُ اللقطات مادّةُ عملٍ لا أمرَ إنتاج.": "<div class=\"band warn\">Eine Shotliste ist Arbeitsmaterial, kein Produktionsauftrag.",
 "<div class=\"band warn\">قيد المراجعة السريريّة": "<div class=\"band warn\">In klinischer Prüfung",
 "<div class=\"band warn\">كلُّ المتطلّبات مرتبطةٌ بأدلّة، ولم تكتمل المراجعتان بعد.": "<div class=\"band warn\">Alle Anforderungen sind belegt; die beiden Prüfungen sind noch nicht abgeschlossen.",
 "<div class=\"band warn\">لا عنصرَ في هذا البناء بعد.": "<div class=\"band warn\">In diesem Build ist noch kein Element.",
 "<div class=\"band warn\">لا مفردةَ واحدة هنا.": "<div class=\"band warn\">Hier ist kein einziger Begriff.",
 "<div class=\"band warn\">مؤشّرُ بدءٍ لا تقييمٌ رسميّ": "<div class=\"band warn\">Eine Orientierung, keine offizielle Bewertung",
 "<div class=\"band warn\">هذا قولُك لا قياسُنا": "<div class=\"band warn\">Das ist Ihre Aussage, nicht unsere Messung",
 "<div class=\"band\">لا شيءَ في المراجعة بعد.": "<div class=\"band\">Noch nichts in der Wiederholung.",
 "<div class=\"band\">لا مستحقَّ اليوم.": "<div class=\"band\">Heute ist nichts fällig.",
 "<div class=\"karte\" id=\"balken\"><h2>تقدّمك</h2>": "<div class=\"karte\" id=\"balken\"><h2>Ihr Fortschritt</h2>",
 "<div class=\"karte\" style=\"margin-top:12px\"><h3>سجّل إجابتك</h3>": "<div class=\"karte\" style=\"margin-top:12px\"><h3>Nehmen Sie Ihre Antwort auf</h3>",
 "<div class=\"karte\"><h2>§ 45 PflAPrV — شكل الامتحان</h2>": "<div class=\"karte\"><h2>§ 45 PflAPrV — die Form der Prüfung</h2>",
 "<div class=\"karte\"><h2>أخطاءٌ تكرّرت</h2>": "<div class=\"karte\"><h2>Fehler, die sich wiederholt haben</h2>",
 "<div class=\"karte\"><h2>الإجابة النموذجيّة</h2><ol>": "<div class=\"karte\"><h2>Musterantwort</h2><ol>",
 "<div class=\"karte\"><h2>الإصابة بحسب المجال</h2>": "<div class=\"karte\"><h2>Treffer nach Kompetenzbereich</h2>",
 "<div class=\"karte\"><h2>الجدولة — كيف تعمل</h2>": "<div class=\"karte\"><h2>Die Wiederholungsplanung — wie sie funktioniert</h2>",
 "<div class=\"karte\"><h2>الحال</h2>": "<div class=\"karte\"><h2>Wo Sie stehen</h2>",
 "<div class=\"karte\"><h2>المقدّمة</h2>": "<div class=\"karte\"><h2>Einleitung</h2>",
 "<div class=\"karte\"><h2>المهمّة</h2>": "<div class=\"karte\"><h2>Die Aufgabe</h2>",
 "<div class=\"karte\"><h2>الوحدات</h2>": "<div class=\"karte\"><h2>Einheiten</h2>",
 "<div class=\"karte\"><h2>تغطية المتطلّبات الرسميّة — ": "<div class=\"karte\"><h2>Abdeckung der offiziellen Anforderungen — ",
 "<div class=\"karte\"><h2>حالةُ المجموعة</h2>": "<div class=\"karte\"><h2>Stand des Kartensatzes</h2>",
 "<div class=\"karte\"><h2>دروس المتعلّم</h2>": "<div class=\"karte\"><h2>Lektionen für Lernende</h2>",
 "<div class=\"karte\"><h2>قائمة اللقطات — لفريق الإنتاج</h2>": "<div class=\"karte\"><h2>Shotliste — für das Produktionsteam</h2>",
 "<div class=\"karte\"><h2>ما أنجزتَه</h2>": "<div class=\"karte\"><h2>Was Sie geschafft haben</h2>",
 "<div class=\"karte\"><h2>ما ستفعله</h2><ol>": "<div class=\"karte\"><h2>Was Sie tun werden</h2><ol>",
 "<div class=\"karte\"><h2>ما قلتَه أنت عن نفسك</h2>": "<div class=\"karte\"><h2>Was Sie selbst über sich gesagt haben</h2>",
 "<div class=\"karte\"><h2>مستحقٌّ اليوم</h2><ul class=\"wh-liste\">": "<div class=\"karte\"><h2>Heute fällig</h2><ul class=\"wh-liste\">",
 "<div class=\"karte\"><h2>مستحقٌّ للمراجعة</h2>": "<div class=\"karte\"><h2>Zur Wiederholung fällig</h2>",
 "<div class=\"karte\"><h2>معايير التقييم</h2>": "<div class=\"karte\"><h2>Bewertungskriterien</h2>",
 "<div class=\"karte\"><h2>هدف المنهج</h2>": "<div class=\"karte\"><h2>Ziel des Curriculums</h2>",
 "<div class=\"karte\"><h2>وبعد؟</h2>": "<div class=\"karte\"><h2>Und dann?</h2>",
 "<div class=\"karte-quellen\">من: ": "<div class=\"karte-quellen\">aus: ",
 "<div class=\"matt\">مخطَّط: ": "<div class=\"matt\">geplant: ",
 "<div class=\"modusband entwicklung\">نسخة تطوير محلّيّة": "<div class=\"modusband entwicklung\">Lokale Entwicklungsfassung",
 "<div class=\"modusband pruefung\">نسخة مراجعة — غير معتمدة للطلاب": "<div class=\"modusband pruefung\">Prüffassung — nicht für Lernende freigegeben",
 "<div class=\"sicher\">ينقصه: ": "<div class=\"sicher\">es fehlt: ",
 "<div class=\"tabellerei\"><table><thead><tr><th>الخطأ</th><th>لماذا</th>": "<div class=\"tabellerei\"><table><thead><tr><th>Fehler</th><th>Warum</th>",
 "<div class=\"tabellerei\"><table><thead><tr><th>المجال</th>": "<div class=\"tabellerei\"><table><thead><tr><th>Bereich</th>",
 "<div class=\"tabellerei\"><table><thead><tr><th>المعيار</th><th>ما الذي يُحسب</th>": "<div class=\"tabellerei\"><table><thead><tr><th>Kriterium</th><th>Was zählt</th>",
 "<h1>اختبارٌ تشخيصيّ — أين تبدأ؟</h1>": "<h1>Diagnostik — wo fangen Sie an?</h1>",
 "<h1>المراجعة — ما يعود إليك اليوم</h1>": "<h1>Wiederholung — was heute zu Ihnen zurückkommt</h1>",
 "<h1>المعاينة الداخليّة</h1>": "<h1>Interne Vorschau</h1>",
 "<h1>المنهج</h1>": "<h1>Curriculum</h1>",
 "<h1>بطاقات المفردات</h1>": "<h1>Vokabelkarten</h1>",
 "<h1>تغطية المتطلّبات الرسميّة</h1>": "<h1>Abdeckung der offiziellen Anforderungen</h1>",
 "<h1>تقدّمك</h1>": "<h1>Ihr Fortschritt</h1>",
 "<h1>محاكاة الامتحان — بوقت</h1>": "<h1>Prüfungssimulation — auf Zeit</h1>",
 "<h1>محاكاة الامتحان</h1>": "<h1>Prüfungssimulation</h1>",
 "<h3>أهداف الحالة — بعد هذه الحالة تستطيع أن…</h3><ul>": "<h3>Lernziele — nach diesem Fall können Sie…</h3><ul>",
 "<h3>أهداف الدرس</h3><ul>": "<h3>Lernziele dieser Lektion</h3><ul>",
 "<h3>ابدأ من هنا</h3>": "<h3>Fangen Sie hier an</h3>",
 "<h3>المطلوب</h3>": "<h3>Ihre Aufgabe</h3>",
 "<h3>بمَ تُقاس هذه المهمّة</h3>": "<h3>Woran diese Aufgabe gemessen wird</h3>",
 "<h3>تمرين — أكمل الفراغ</h3>": "<h3>Übung — Lücke füllen</h3>",
 "<h3>تمرين — رتّب خطوات الإجراء</h3>": "<h3>Übung — die Schritte ordnen</h3>",
 "<h3>ما الذي تستطيعه الآن؟</h3>": "<h3>Was können Sie jetzt?</h3>",
 "<h3>ما لم تُصِبه</h3><ul>": "<h3>Was Sie nicht getroffen haben</h3><ul>",
 "<h3>يُراجَع</h3><ul>": "<h3>Zu wiederholen</h3><ul>",
 "<label class=\"klein matt\">سرعة الفيديو</label>": "<label class=\"klein matt\">Videotempo</label>",
 "<label class=\"klein matt\">ظهورها</label>": "<label class=\"klein matt\">Anzeige</label>",
 "<label class=\"klein matt\">وجهُ البطاقة</label>": "<label class=\"klein matt\">Kartenvorderseite</label>",
 "<li>أسئلةٌ مكتوبة: ": "<li>Schriftliche Fragen: ",
 "<li>لم تعرف ": "<li>Nicht gewusst: ",
 "<li>محطّةٌ شفهيّة: ": "<li>Eine mündliche Station: ",
 "<li>محطّةٌ عمليّة: ": "<li>Eine praktische Station: ",
 "<option value=\"an\">كاملة</option>": "<option value=\"an\">immer</option>",
 "<option value=\"ar\">عربيّ ← ألمانيّ</option></select></div>": "<option value=\"ar\">Übersetzung → Deutsch</option></select></div>",
 "<option value=\"aus\">مخفيّة</option></select>": "<option value=\"aus\">ausgeblendet</option></select>",
 "<option value=\"de\">ألمانيّ ← عربيّ</option>": "<option value=\"de\">Deutsch → Übersetzung</option>",
 "<option value=\"klick\">عند الطلب</option>": "<option value=\"klick\">auf Tippen</option>",
 "<p class=\"klein matt l-entwurf\">جملةٌ مسوّدةٌ من البرنامج — ": "<p class=\"klein matt l-entwurf\">Ein Entwurfssatz des Programms — ",
 "<p class=\"klein matt s-frage\">كيف تسمع محاولتك؟</p>": "<p class=\"klein matt s-frage\">Wie klingt Ihr Versuch für Sie?</p>",
 "<p class=\"klein matt\">احكم على نفسِك — <b>لا تصحيحَ آليّاً للنطق هنا</b>، ": "<p class=\"klein matt\">Beurteilen Sie sich selbst — <b>eine automatische Aussprachebewertung gibt es hier nicht</b>, ",
 "<p class=\"klein matt\">التسجيلُ يبقى في متصفّحك: لا يُرفع، ولا يُحفَظ في ملفّ، ": "<p class=\"klein matt\">Die Aufnahme bleibt in Ihrem Browser: nichts wird hochgeladen, nichts in eine Datei geschrieben, ",
 "<p class=\"klein matt\">الجملُ مأخوذةٌ من الجدول فوقَه كما هي. ": "<p class=\"klein matt\">Die Sätze stammen unverändert aus der Tabelle darüber. ",
 "<p class=\"klein matt\">الزمن: ": "<p class=\"klein matt\">Zeit: ",
 "<p class=\"klein matt\">القسم: ": "<p class=\"klein matt\">Teil: ",
 "<p class=\"klein matt\">المجموع ": "<p class=\"klein matt\">Gesamt ",
 "<p class=\"klein matt\">المستندُ الكامل: <code>drehbuch/": "<p class=\"klein matt\">Vollständiges Dokument: <code>drehbuch/",
 "<p class=\"klein matt\">بالترتيب الذي تنفّذها به. ": "<p class=\"klein matt\">In der Reihenfolge, in der Sie sie durchführen. ",
 "<p class=\"klein matt\">بترتيب الدورة، ولكلّ عنصرٍ سببُ ترشيحه: ": "<p class=\"klein matt\">In der Reihenfolge des Kurses, und jedes Element nennt seinen Grund: ",
 "<p class=\"klein matt\">بمعايير هذه المحطّة كما هي في المحتوى. ": "<p class=\"klein matt\">Nach den Kriterien dieser Station, wie sie im Inhalt stehen. ",
 "<p class=\"klein matt\">تحت كلّ سؤالٍ أخطأتَه سببُ الخطأ ": "<p class=\"klein matt\">Unter jeder falsch beantworteten Frage steht der Grund des Fehlers ",
 "<p class=\"klein matt\">تركيبُ هذه الإجابة ومعاييرُها <b>مسوّدة</b> ": "<p class=\"klein matt\">Wie diese Antwort und ihre Kriterien zusammengesetzt wurden, ist ein <b>Entwurf</b> ",
 "<p class=\"klein matt\">حكمُك أنت، لا درجةٌ تُحسَب لك. ": "<p class=\"klein matt\">Ihr eigenes Urteil, keine Note. ",
 "<p class=\"klein matt\">ربطُ الأهداف بمواضع قياسها <b>مسوّدة</b> ": "<p class=\"klein matt\">Die Zuordnung der Lernziele zu ihren Prüforten ist ein <b>Entwurf</b> ",
 "<p class=\"klein matt\">لا نصَّ جديداً هنا: هذه مقاطعُ من الحالة ": "<p class=\"klein matt\">Hier steht nichts Neues: das sind Ausschnitte aus dem Fall ",
 "<p class=\"klein matt\">ما أخطأتَ فيه مرّتين فأكثرَ في المراجعة.</p>": "<p class=\"klein matt\">Was Sie in der Wiederholung zweimal oder öfter falsch hatten.</p>",
 "<p class=\"klein matt\">معاييرُ هذه الحالة نفسُها — لا معاييرُ ": "<p class=\"klein matt\">Die Kriterien dieses Falls selbst — keine anderen Kriterien ",
 "<p class=\"klein matt\">من أسئلة الاختبارات والتشخيص. سؤالٌ له ": "<p class=\"klein matt\">Aus den Quizfragen und der Diagnostik. Eine Frage hat ",
 "<p class=\"klein matt\">هذا حكمُك أنت على نطقك، لا قياسٌ آليّ.</p>": "<p class=\"klein matt\">Das ist Ihr eigenes Urteil über Ihre Aussprache, keine Messung.</p>",
 "<p class=\"klein matt\">هذا كلُّ ما يمكن تصحيحُه آليّاً. والمحطّتان ": "<p class=\"klein matt\">Mehr lässt sich nicht automatisch bewerten. Die beiden Stationen ",
 "<p class=\"klein matt\">وحدةٌ واحدة: <span class=\"chip\">": "<p class=\"klein matt\">Nur eine Einheit: <span class=\"chip\">",
 "<p class=\"klein matt\">يثبت ": "<p class=\"klein matt\">belegt ",
 "<p class=\"klein\"><span class=\"chip warn\">مصادر مسوّدة</span> ": "<p class=\"klein\"><span class=\"chip warn\">Entwurfsquellen</span> ",
 "<p class=\"matt\">اثنا عشر سؤالاً مأخوذةً من اختبارات الوحدات، ": "<p class=\"matt\">Zwölf Fragen aus den Quizze der Einheiten, ",
 "<p class=\"matt\">تكرارٌ متباعد بصناديق. البطاقةُ التي تعرفها ترتفع صندوقاً ": "<p class=\"matt\">Verteilte Wiederholung mit Boxen. Eine Karte, die Sie können, rückt eine Box höher ",
 "<p class=\"matt\">كلُّ ما في هذه الصفحة من متصفّحك وحدَه: لا حساب، ": "<p class=\"matt\">Alles auf dieser Seite kommt allein aus Ihrem Browser: kein Konto, ",
 "<p class=\"matt\">كلُّ متطلَّبٍ رسميّ مربوطٌ بأربعة عناصر: درسٌ معرفيّ، وحالةٌ تطبيقيّة، ": "<p class=\"matt\">Jede offizielle Anforderung hängt an vier Elementen: einer Wissenslektion, einem angewandten Fall, ",
 "<p class=\"matt\">لا خطأَ تكرّر — أو لم تراجع بعد.</p>": "<p class=\"matt\">Kein Fehler hat sich wiederholt — oder Sie haben noch nicht wiederholt.</p>",
 "<p class=\"matt\">لا فيلمَ كاملاً بعد. وهذا <b>مقطعٌ تجريبيٌّ</b> من مشهدٍ واحد:</p>": "<p class=\"matt\">Noch kein vollständiger Film. Dies ist ein <b>Probeausschnitt</b> aus einer einzigen Szene:</p>",
 "<p class=\"matt\">لا ملفّ فيديو بعد. <code>media/</code> خارج المستودع، ": "<p class=\"matt\">Noch keine Videodatei. <code>media/</code> liegt außerhalb des Repositoriums, ",
 "<p class=\"matt\">لا يدخل هنا إلّا ما فعلتَه أنت: سؤالٌ أخطأتَه، ": "<p class=\"matt\">Hierher kommt nur, was Sie selbst getan haben: eine Frage, die Sie falsch hatten, ",
 "<p class=\"matt\">لم تُجِب عن اختبارٍ بعد.</p>": "<p class=\"matt\">Sie haben noch kein Quiz bearbeitet.</p>",
 "<p class=\"matt\">لم تُقسَّم المشاهد بعد. البنيةُ <code>film.szenen[]</code> جاهزة ": "<p class=\"matt\">Die Szenen sind noch nicht geschnitten. Die Struktur <code>film.szenen[]</code> steht bereit ",
 "<p class=\"quelle\">§ 45 PflAPrV ومجالات الكفاءة I–V في Anlage 2 — ": "<p class=\"quelle\">§ 45 PflAPrV und die Kompetenzbereiche I–V der Anlage 2 — ",
 "<p class=\"quelle\">اسمع المصطلح، ثمّ سجّل نفسَك وقارن. ": "<p class=\"quelle\">Hören Sie den Begriff, nehmen Sie sich dann selbst auf und vergleichen Sie. ",
 "<p class=\"quelle\">المعلومةُ الواحدة بثلاثة أساليب.</p>": "<p class=\"quelle\">Eine Information, drei Register.</p>",
 "<p class=\"quelle\">بعضُ السطورِ لها تسجيل. والأصواتُ مركَّبةٌ لا بشريّة.</p>": "<p class=\"quelle\">Manche Zeilen haben eine Aufnahme. Die Stimmen sind synthetisch, nicht menschlich.</p>",
 "<p class=\"quelle\">لكلّ سطرٍ تسجيلُه. والأصواتُ مركَّبةٌ لا بشريّة.</p>": "<p class=\"quelle\">Jede Zeile hat ihre eigene Aufnahme. Die Stimmen sind synthetisch, nicht menschlich.</p>",
 "<p class=\"quelle-klein\">المصدر: ": "<p class=\"quelle-klein\">Quelle: ",
 "<p class=\"sicher\">السلامة: ": "<p class=\"sicher\">Sicherheit: ",
 "<p><a href=\"#/abdeckung\">افتح المصفوفة كاملةً ←</a></p></div>": "<p><a href=\"#/abdeckung\">Die ganze Matrix öffnen →</a></p></div>",
 "<p><a href=\"#/wiederholung\">افتح المراجعة</a></p></div>": "<p><a href=\"#/wiederholung\">Die Wiederholung öffnen</a></p></div>",
 "<p>أصبتَ كلَّ الأسئلة. وهذا لا يعني أنّك لا تحتاج الدورة: ": "<p>Sie haben alle Fragen richtig. Das heißt nicht, dass Sie den Kurs nicht brauchen: ",
 "<p>ما أخطأتَه من الأسئلة يدخل <a href=\"#/wiederholung\">المراجعة</a> ": "<p>Die Fragen, die Sie falsch hatten, kommen von selbst in <a href=\"#/wiederholung\">die Wiederholung</a> ",
 "<p>ما تعرفه يرتفع صندوقاً فيتباعد موعدُه، وما تنساه يعود إلى ": "<p>Was Sie können, rückt eine Box höher und kommt entsprechend später wieder; was Sie vergessen, kehrt zurück in ",
 "<span class=\"chip frei\">معتمد سريريّاً ومنهجيّاً</span>": "<span class=\"chip frei\">klinisch und curricular freigegeben</span>",
 "<span class=\"chip offen\">غير مغطّى</span>": "<span class=\"chip offen\">ohne Abdeckung</span>",
 "<span class=\"chip rot\">سلامة</span>": "<span class=\"chip rot\">Sicherheit</span>",
 "<span class=\"chip warn\">لغة</span>": "<span class=\"chip warn\">Sprache</span>",
 "<span class=\"klein\">«مرتبط بأدلّة» يعني أنّ الرابط سليمُ الشكل: المسارُ موجودٌ ": "<span class=\"klein\">„Belegt“ heißt, der Verweis ist formal in Ordnung: der Pfad existiert ",
 "<span class=\"klein\">اثنا عشر سؤالاً لا تقيس مستواك اللغويّ، ": "<span class=\"klein\">Zwölf Fragen messen Ihr Sprachniveau nicht, ",
 "<span class=\"klein\">البطاقاتُ تُشتقّ من <code>vokabeln[]</code> في المحتوى، ": "<span class=\"klein\">Die Karten werden aus <code>vokabeln[]</code> im Inhalt abgeleitet, ",
 "<span class=\"klein\">البنودُ كلُّها مجدوَلةٌ في المستقبل. ": "<span class=\"klein\">Alle Posten sind für später terminiert. ",
 "<span class=\"klein\">انقضى وقتُ الجولة، وما أجبتَ عنه محفوظ. ": "<span class=\"klein\">Die Zeit der Runde ist abgelaufen, und was Sie beantwortet haben, ist gespeichert. ",
 "<span class=\"klein\">تدخل البنودُ هنا وحدَها: بعد اختبارِ وحدةٍ ": "<span class=\"klein\">Die Posten kommen von selbst hierher: nach einem Quiz einer Einheit, ",
 "<span class=\"klein\">حكمُك على نطقك وإقرارُك بالأهداف رأيُك أنت. ": "<span class=\"klein\">Ihr Urteil über Ihre Aussprache und Ihre Bestätigung der Lernziele sind Ihre eigene Sicht. ",
 "<span class=\"klein\">شغّل <code>tools/bau.py</code>.</span></div>": "<span class=\"klein\">Führen Sie <code>tools/bau.py</code> aus.</span></div>",
 "<span class=\"klein\">عُد غداً، أو اختر وحدةً بعينها من صفحتها.</span></div>": "<span class=\"klein\">Kommen Sie morgen wieder, oder wählen Sie eine bestimmte Einheit auf ihrer Seite.</span></div>",
 "<span class=\"klein\">كلُّ ما في هذه الصفحة غيرُ معتمد. لا يُعرض على مرشّحٍ، ": "<span class=\"klein\">Nichts auf dieser Seite ist freigegeben. Es wird keiner Kandidatin und keinem Kandidaten gezeigt, ",
 "<span class=\"klein\">لا يُعلَن الاكتمالُ ما بقيت فجوة. ولا يُعَدُّ المتطلّبُ مغطًّى ": "<span class=\"klein\">Vollständigkeit wird nicht erklärt, solange eine Lücke bleibt. Und eine Anforderung gilt nicht als abgedeckt ",
 "<span class=\"klein\">لا يُنتَج فيديو ولا يُربَط بالمحتوى قبل أن يقبله ": "<span class=\"klein\">Kein Video wird produziert oder in den Inhalt eingebunden, bevor es angenommen hat ",
 "<span class=\"klein\">مشتقّةٌ من محتوًى غيرِ مراجَع. لا تُعرض على مرشّح.</span></div>": "<span class=\"klein\">Aus ungeprüftem Inhalt abgeleitet. Nicht für Kandidatinnen und Kandidaten.</span></div>",
 "<span class=\"klein\">هذا العنصر غيرُ معتمد. المصدر: ": "<span class=\"klein\">Dieses Element ist nicht freigegeben. Quelle: ",
 "<span class=\"klein\">هذه محاكاةٌ من محتوى الدورة على بنية ": "<span class=\"klein\">Dies ist eine Simulation aus den Kursinhalten nach der Struktur von ",
 "<span class=\"matt\">لا شيء</span>": "<span class=\"matt\">nichts</span>",
 "<span>كلُّ ما فيها مسوّدةٌ لم تُراجَع سريريّاً ولا منهجيّاً. ": "<span>Alles darin ist Entwurf, weder klinisch noch curricular geprüft. ",
 "<span>ليست نسخةَ طلّابٍ ولا نسخةَ مراجعةٍ منشورة.</span></div>": "<span>Das ist weder eine Lernfassung noch eine veröffentlichte Prüffassung.</span></div>",
 "<th>#</th><th>المشهد</th><th>الزمن</th><th>اللقطة</th><th>أسطر الحوار</th>": "<th>#</th><th>Szene</th><th>Zeit</th><th>Einstellung</th><th>Dialogzeilen</th>",
 "<th>#</th><th>الوحدة</th><th>متطلّبات</th><th>الحال</th><th>ما بُني</th>": "<th>#</th><th>Einheit</th><th>Anforderungen</th><th>Stand</th><th>Gebaut</th>",
 "<th>أصبتَ</th></tr></thead><tbody>": "<th>Richtig</th></tr></thead><tbody>",
 "<th>الألمانيّة</th><th>العربيّة</th><th>مع المريض</th><th>مع الفريق</th><th>في التوثيق</th>": "<th>Deutsch</th><th>Übersetzung</th><th>Mit dem Patienten</th><th>Im Team</th><th>In der Dokumentation</th>",
 "<th>الصواب</th><th>النوع</th></tr></thead><tbody>": "<th>Stattdessen</th><th>Art</th></tr></thead><tbody>",
 "<th>المجال</th><th>أصبتَ</th><th></th></tr></thead><tbody>": "<th>Bereich</th><th>Richtig</th><th></th></tr></thead><tbody>",
 "<th>المعرّف</th><th>المتطلَّب</th><th>الحالة</th><th>ما ينقص</th><th>الأدلّة</th>": "<th>Kennung</th><th>Anforderung</th><th>Stand</th><th>Was fehlt</th><th>Belege</th>",
 "<ul><li>عرفتَ ": "<ul><li>Gewusst: ",
 "A — التقدير": "A — Assessment",
 "B — الخلفيّة": "B — Background",
 "I — التعريف": "I — Identifikation",
 "R — الطلب": "R — Recommendation",
 "S — الموقف": "S — Situation",
 "Togetherwecan Jobs · المحتوى محلّيٌّ بالكامل، لا يغادر هذا الجهاز<br>": "Togetherwecan Jobs · alles hier ist lokal und verlässt dieses Gerät nicht<br>",
 "{n} يوماً": "{n} Tage",
 "§ 45 PflAPrV. <b>ليست امتحاناً، ولا تقييماً رسميّاً، ولا اعتماداً، ": "§ 45 PflAPrV. <b>Sie ist keine Prüfung, keine offizielle Bewertung, keine Anerkennung ",
 "» بدقّة.": "» genau ausgesprochen.",
 "، ": ", ",
 "، فعادت إلى الصندوق الأوّل.</li></ul></div>": ", die in die erste Box zurückgefallen sind.</li></ul></div>",
 "آخر جولة: ": "Letzte Runde: ",
 "آخر نتيجة: ": "Letztes Ergebnis: ",
 "أجب عن كلّ الأسئلة أوّلاً — بقي ": "Beantworten Sie zuerst alle Fragen — es fehlen noch ",
 "أجزاء الامتحان — § 45 PflAPrV": "Prüfungsteile — § 45 PflAPrV",
 "أحد الأقارب": "Angehörige/r",
 "أخرى كُتبت للمهمّة.</p><ul>": "eigens für die Aufgabe geschrieben.</p><ul>",
 "أخطأتَ فيه ": "falsch gehabt: ",
 "أخطأتَه في اختبار الوحدة": "Im Quiz der Einheit falsch gehabt",
 "أخطأتَه في الاختبار التشخيصيّ": "In der Diagnostik falsch gehabt",
 "أخفِ ما فوق": "Oberes ausblenden",
 "أسطر الحوار": "Dialogzeilen",
 "أصبتَ": "Richtig",
 "أصبتَ ": "Richtig ",
 "أظهِر النتيجة": "Ergebnis zeigen",
 "أظهِر ما فوق": "Oberes einblenden",
 "أعد ضبط جدولة المراجعة": "Wiederholungstermine zurücksetzen",
 "أعِد مرّةً واحدةً وقارن التسجيلين؛ إن تساويا فانتقل.": "Machen Sie es noch einmal und vergleichen Sie die beiden Aufnahmen; klingen sie gleich, gehen Sie weiter.",
 "أقررتَ بـ": "Bestätigt: ",
 "أقسامٌ علّمتَ أنّها تمّت": "Abschnitte, die Sie als erledigt markiert haben",
 "أنهِ الآن": "Jetzt beenden",
 "أهدافٌ قلتَ إنّك تستطيعها": "Lernziele, die Sie sich zutrauen",
 "أين أبدأ": "Wo anfangen",
 "إجاباتُك تُحفَظ أوّلاً بأوّل في متصفّحك، فلا يضيع شيءٌ بالانقطاع.": "Ihre Antworten werden laufend in Ihrem Browser gespeichert, eine Unterbrechung verliert also nichts.",
 "ابدأ الجولة": "Runde starten",
 "اثنا عشر سؤالاً لا تغطّي اثنين وتسعين متطلَّباً. ابدأ من أوّلها.</p>": "zwölf Fragen decken keine zweiundneunzig Anforderungen ab. Fangen Sie vorne an.</p>",
 "احذف الجولة": "Runde verwerfen",
 "اختباراتُ وحداتٍ أدّيتَها": "Bearbeitete Quizze der Einheiten",
 "اختر إجابةً واحدة": "Eine Antwort wählen",
 "اختر كلَّ ما ينطبق": "Alles Zutreffende wählen",
 "اسمع": "Anhören",
 "اسمع النموذجَ مرّةً، ثمّ أعِد على مَهَلٍ — الوضوحُ قبل السرعة.": "Hören Sie das Modell einmal, dann noch einmal in Ruhe — Deutlichkeit vor Tempo.",
 "اسمع النموذجَ مرّةً، ثمّ أعِد وركّز على نقطةٍ واحدة: ": "Hören Sie das Modell einmal, dann noch einmal mit Blick auf einen einzigen Punkt: ",
 "اسمع تسجيلك": "Ihre Aufnahme anhören",
 "اطُّلع عليه ": "abgerufen am ",
 "اكتب المصطلحَ الناقص، والخياراتُ عند الحاجة.</p>": "Schreiben Sie den fehlenden Begriff; die Optionen stehen bereit, falls Sie sie brauchen.</p>",
 "الأدلّة": "Belege",
 "الأسئلة المكتوبة": "Die schriftlichen Fragen",
 "الأكسجة": "SpO₂",
 "الألمانيّة": "Deutsch",
 "الاختبار: ": "Quiz: ",
 "الاسم": "Name",
 "البطاقات": "Karten",
 "التسجيل يحتاج خادماً محلّيّاً (http://localhost).": "Die Aufnahme braucht einen lokalen Server (http://localhost).",
 "التسجيل يحتاج صفحةً على http://localhost — لا ملفّاً مفتوحاً ": "Die Aufnahme braucht eine Seite unter http://localhost — keine Datei, die ",
 "التشخيص": "Diagnose",
 "التغطية": "Abdeckung",
 "الجنس": "Geschlecht",
 "الحال": "Stand",
 "الحالة": "Stand",
 "الحرارة": "Temp.",
 "الخطأ": "Fehler",
 "الخيارات": "Optionen",
 "الدورة": "Kurs",
 "الزمن": "Zeit",
 "السؤال المهنيّ ": "Fachfrage ",
 "الصندوق ": "Box ",
 "الصندوق الأوّل. والفواصلُ بالأيّام:</p>": "die erste Box. Die Abstände in Tagen:</p>",
 "الصواب": "Stattdessen",
 "الصواب: ": "Richtig wäre: ",
 "الطبيب/ة": "Ärztin/Arzt",
 "العربيّة": "Arabisch",
 "العمر": "Alter",
 "القسم": "Station",
 "اللقطة": "Einstellung",
 "المتطلَّب": "Anforderung",
 "المتطلَّبُ الذي أخطأتَ سؤالَه وهذا العنصرُ يثبته.</p><ol class=\"dg-weg\">": "die Anforderung, deren Frage Sie verfehlt haben, und dieses Element belegt sie.</p><ol class=\"dg-weg\">",
 "المجال": "Bereich",
 "المحاولة ": "Versuch ",
 "المحاولة رقم ": "Versuch Nummer ",
 "المحطّة الشفهيّة": "Die mündliche Station",
 "المحطّة العمليّة": "Die praktische Station",
 "المراجعة": "Wiederholung",
 "المريض": "Patient/in",
 "المستحقُّ اليوم: ": "Heute fällig: ",
 "المسوّدة.</span></div>": "Entwurf sind.</span></div>",
 "المشهد": "Szene",
 "المعاينة الداخليّة": "Interne Vorschau",
 "المعرّف": "Kennung",
 "المعنى: ": "Bedeutung: ",
 "المعيار": "Kriterium",
 "الممرّض/ة": "Pflegefachkraft",
 "المنهج": "Curriculum",
 "النبض": "Puls",
 "النتيجة": "Ergebnis",
 "النوع": "Art",
 "الوحدة": "Einheit",
 "الوقت": "Zeit",
 "الوقت كلُّه: ": "Gesamtzeit: ",
 "اليوم": "heute",
 "امسح التشخيص": "Diagnostik löschen",
 "انتقل إلى السطر التالي — وسيعود هذا السطرُ في المراجعة.": "Gehen Sie zur nächsten Zeile — diese kommt in der Wiederholung zurück.",
 "انتهى. التسجيلُ في متصفّحك وحدَه.": "Beendet. Die Aufnahme bleibt allein in Ihrem Browser.",
 "بطاقاتُ هذه الوحدة (": "Karten dieser Einheit (",
 "بطاقةٍ تنساها.</span></div>": "einer Karte, die Sie vergessen.</span></div>",
 "بعد {n} يوماً": "in {n} Tagen",
 "بعد يوم": "morgen",
 "بقيت بنودٌ لم تُقِرَّ بها في تقييمك الذاتيّ": "In Ihrer Selbstprüfung sind Punkte offen geblieben",
 "بنودُ تقييمٍ ذاتيٍّ أقررتَ بها": "Bestätigte Punkte der Selbstprüfung",
 "بُني بـ <code>tools/bau.py</code> — لا تُحرَّر <code>app/daten*.js</code> بيدك</div>": "Erzeugt mit <code>tools/bau.py</code> — <code>app/daten*.js</code> nicht von Hand ändern</div>",
 "تحقّق": "Prüfen",
 "تدريب": "Training",
 "تعذّر التسجيل: ": "Aufnahme nicht möglich: ",
 "تعذّر تحميل daten-intern.js — شغّل tools/bau.py.": "daten-intern.js konnte nicht geladen werden — führen Sie tools/bau.py aus.",
 "تقدّمي": "Mein Fortschritt",
 "تقيسهما بنفسك تحت، ولا يُجمَع الاثنان في درجةٍ واحدة.</p>": "beurteilen Sie unten selbst, und beides wird nicht zu einer Note verrechnet.</p>",
 "تقييم": "Bewertung",
 "تلك هي المراجعة المنهجيّة، وإلى جانبها السريريّة على المضمون.</span></div>": "Das ist die curriculare Prüfung; daneben steht die klinische Prüfung des Inhalts.</span></div>",
 "تمّ ✓": "Erledigt ✓",
 "تنتظر مراجعةَ مدرّس.</p>": "und wartet auf die Prüfung durch eine Lehrkraft.</p>",
 "تنتظر مراجعةَ مدرّسٍ أو مختصّ.</p>": "und wartet auf die Prüfung durch eine Lehrkraft oder Fachperson.</p>",
 "تنتظر مراجعةَ مدرّسٍ مؤهَّل.</p>": "und wartet auf die Prüfung durch eine qualifizierte Lehrkraft.</p>",
 "تُخطئ فيه، أو بعد أن تحكم على نطقك في حلقة الكلام، أو بعد ": "das Sie falsch hatten, nachdem Sie Ihre Aussprache in der Sprechschleife beurteilt haben, oder nach ",
 "ثمّ أعد المحاولة. ولا شيء يُرسَل في الحالتين.": "und versuchen Sie es erneut. In beiden Fällen wird nichts gesendet.",
 "جارٍ التحميل…": "Wird geladen …",
 "جديدٌ في المراجعة": "Neu in der Wiederholung",
 "جلسةٌ جديدة</button></div>": "Neue Sitzung</button></div>",
 "جملةٌ منطوقة": "Gesprochener Satz",
 "جملٌ سجّلتَ نطقَها": "Sätze, die Sie selbst gesprochen aufgenommen haben",
 "جوابٌ صائبٌ واحد، فهذه وقائعُ لا تقدير.</p>": "genau eine richtige Antwort — das sind Fakten, keine Schätzungen.</p>",
 "جولةٌ جديدة": "Neue Runde",
 "حالة": "Fall",
 "حالة تطبيقيّة": "Angewandter Fall",
 "حكمتَ على نطقك: يحتاج إعادة": "Ihr Urteil über Ihre Aussprache: noch einmal",
 "درس معرفيّ": "Wissenslektion",
 "دورة التحضير لامتحان المعرفة في التمريض — Togetherwecan Jobs": "Kenntnisprüfung Pflege — Vorbereitungskurs · Togetherwecan Jobs",
 "رابطٌ سليمُ الشكل، بلا مراجعةٍ بشريّة بعد": "Formal gültiger Verweis, noch ohne menschliche Prüfung",
 "راجِع: ": "Wiederholen: ",
 "رفعتُ نبرةَ السؤال ووقفتُ عند آخرِه.": "Ich habe die Frageintonation gehoben und am Ende eine Pause gemacht.",
 "زميل/ة من مهنةٍ أخرى": "Kollegin/Kollege aus einem anderen Beruf",
 "سؤال": "Frage",
 "سؤال الاختبار ": "Quizfrage ",
 "سؤالان من كلّ مجال. تُجيب مرّةً، فتعرف أيَّ المجالات تحتاج ": "zwei aus jedem Bereich. Sie antworten einmal und sehen, welche Bereiche mehr ",
 "سابقاً: ": "Bisher: ",
 "سجّل نفسك": "Sich selbst aufnehmen",
 "سريريّ": "klinisch",
 "سُجّل — في متصفّحك وحدَه.": "Aufgenommen — allein in Ihrem Browser.",
 "سُجّل — في متصفّحك وحدَه، ويزول بإغلاق الصفحة.": "Aufgenommen — allein in Ihrem Browser, und beim Schließen der Seite verschwindet es.",
 "شفهيّ": "mündlich",
 "صحيح: ": "Richtig: ",
 "صندوق ": "Box ",
 "ض. الدم": "RR",
 "عامّ": "allgemein",
 "عرفتُه الآن": "Jetzt gewusst",
 "علّم أنّه تمّ": "Als erledigt markieren",
 "عمليّ": "praktisch",
 "عناصرُ بدأتَها": "Begonnene Elemente",
 "غير مراجَع": "ungeprüft",
 "في التوثيق": "In der Dokumentation",
 "في التوثيق: ": "In der Dokumentation: ",
 "في هذه الإعادة ركّزتُ على نقطةٍ واحدةٍ وقارنتُها بالمحاولة السابقة.": "In diesem Versuch habe ich auf einen einzigen Punkt geachtet und ihn mit dem vorigen verglichen.",
 "فيتباعد موعدُها، والتي تنساها تعود إلى الأوّل.</p>": "und ihr Termin rückt weiter weg; eine vergessene Karte fällt zurück in die erste.</p>",
 "فيديو مرفوض": "Video abgelehnt",
 "فيديو مسوّدة": "Video Entwurf",
 "فيديو مقبول": "Video angenommen",
 "قبل أن تجتمع عليه العناصرُ الأربعة: درسٌ معرفيّ، وحالةٌ تطبيقيّة، وتدريبٌ، ومعيارُ تقييم.</span></div>": "bevor alle vier Elemente zusammenkommen: eine Wissenslektion, ein angewandter Fall, ein Training und ein Bewertungskriterium.</span></div>",
 "قبل أن تنتقل، أعِد مرّةً واحدةً من أجل: ": "Bevor Sie weitergehen: noch einmal, diesmal für: ",
 "قريب. أعِد مرّةً واحدةً من أجل: ": "Nah dran. Noch einmal, diesmal für: ",
 "قلتَ عنها: مقبول": "Von Ihnen als „in Ordnung“ beurteilt",
 "قلتَ عنها: واثق": "Von Ihnen als „sicher“ beurteilt",
 "قلتَ عنها: يحتاج إعادة": "Von Ihnen als „noch einmal“ beurteilt",
 "قلتُ الجملةَ كاملةً دون حذفِ المعنى.": "Ich habe den ganzen Satz gesagt, ohne etwas vom Sinn wegzulassen.",
 "قيد المراجعة": "in Prüfung",
 "قيّم نفسَك في ": "Beurteilen Sie sich in ",
 "كان نطقي مفهوماً من أوّلِ سماع.": "Meine Aussprache war beim ersten Hören verständlich.",
 "لأسفل": "Nach unten",
 "لأعلى": "Nach oben",
 "لأنّك أخطأتَ: ": "Weil Sie falsch hatten: ",
 "لا فيديو مقبول": "kein angenommenes Video",
 "لا مادّةَ لها في هذه الحالة، ولم يُكتَب لها جوابٌ من الاجتهاد. ": "Dieser Fall hat dafür kein Material, und es wurde keine Antwort dazu erfunden. ",
 "لا ميكروفونَ متاح على هذا الجهاز.": "Auf diesem Gerät ist kein Mikrofon verfügbar.",
 "لا يمكن اعتمادُ هذا العنصر قبل إكمال كلّ مصدرٍ فيه.</p>": "Dieses Element kann nicht freigegeben werden, solange nicht jede Quelle darin vollständig ist.</p>",
 "لا يمكن بناءُ التشخيص.</div>": "die Diagnostik lässt sich nicht bauen.</div>",
 "لا يُجمَع مع ما فوقَه في رقمٍ واحد، ولا يصير درجةً، ": "Es wird nicht mit den Zahlen darüber zu einer Zahl verrechnet, es wird keine Note, ",
 "للفريق والمراجِعين وحدَهم، ولا تُقدَّم إلى طالبٍ بوصفها مادّةً معتمدة.</span></div>": "Nur für das Team und die Prüfenden; es wird Lernenden nicht als freigegebenes Material vorgelegt.</span></div>",
 "لم يُؤذن باستعمال الميكروفون. اسمح للصفحة به من إعدادات المتصفّح ": "Die Mikrofonberechtigung wurde verweigert. Erlauben Sie sie dieser Seite in den Browsereinstellungen ",
 "لم يُؤذن بالميكروفون. ولا شيءَ يُرسَل في الحالتين.": "Das Mikrofon wurde nicht erlaubt. Gesendet wird in beiden Fällen nichts.",
 "لماذا": "Warum",
 "لماذا هنا: ": "Warum hier: ",
 "ما الذي يُحسب": "Was zählt",
 "ما بُني": "Gebaut",
 "ما جرى.</p>": "was passiert ist.</p>",
 "ما زال صعباً": "Noch schwer",
 "ما ينقص": "Was fehlt",
 "مباشرةً بـ file://. شغّل: python3 -m http.server 8131": "direkt über file:// geöffnet wurde. Führen Sie aus: python3 -m http.server 8131",
 "متصفّحك لا يتيح التسجيل هنا.": "Ihr Browser erlaubt hier keine Aufnahme.",
 "متطلّبات": "Anforderungen",
 "محاكاة": "Simulation",
 "محاولاتُ نطقٍ": "Sprechversuche",
 "محاولةٌ جديدة بأسئلةٍ أخرى": "Neuer Versuch mit anderen Fragen",
 "محطّة تدريب": "Trainingsstation",
 "محمد فيصير حالُه <code>angenommen</code> في <code>curriculum/medien.json</code>. ": "und sein Status in <code>curriculum/medien.json</code> auf <code>angenommen</code> steht. ",
 "مراجعة سريريّة": "klinische Prüfung",
 "مراجعة منهجيّة": "curriculare Prüfung",
 "مرتبط بأدلّة</span>": "belegt</span>",
 "مسوّدة — غير مُثبَت": "Entwurf — nicht belegt",
 "مصادر ناقصة": "unvollständige Quellen",
 "مع الفريق": "Im Team",
 "مع المريض": "Mit dem Patienten",
 "مع المريض: ": "Mit dem Patienten: ",
 "معتمد": "freigegeben",
 "معيار ": "Kriterium ",
 "معيار المؤسّسة": "Hausstandard",
 "معيار مهنيّ": "Fachstandard",
 "مغطّى كلُّه": "vollständig abgedeckt",
 "مفردة": "Begriff",
 "مفردةٌ أخطأتَ فيها في البطاقات": "Ein Begriff, den Sie bei den Karten falsch hatten",
 "مقبول": "In Ordnung",
 "من ": "aus ",
 "من تلقاء نفسِه. و<a href=\"#/fortschritt\">لوحةُ التقدّم</a> تعرض ": "von selbst. Und <a href=\"#/fortschritt\">die Fortschrittsseite</a> zeigt ",
 "منها فوق حدّ النجاح": "davon über der Bestehensgrenze",
 "منهجيّ": "curricular",
 "نافذٌ من ": "gültig ab ",
 "نتيجةُ الجزء المصحَّح آليّاً": "Ergebnis des automatisch bewerteten Teils",
 "نصّ قانونيّ": "Gesetzestext",
 "نطقتُ الأرقامَ والجرعاتِ كما هي، رقماً رقماً.": "Ich habe Zahlen und Dosierungen genau gesagt, Ziffer für Ziffer.",
 "نطقتُ الأرقامَ والمصطلحَ «": "Ich habe die Zahlen und den Begriff «",
 "نطقتُ الكلماتِ المهنيّةَ بدقّة.": "Ich habe die Fachwörter genau ausgesprochen.",
 "نطقتُ المصطلحَ المهنيَّ «": "Ich habe den Fachbegriff «",
 "نفسِها، ومكانُ كلٍّ منها مكتوبٌ تحته. حاوِل أوّلاً ثمّ افتح.</p>": "selbst, und unter jedem steht, woher es stammt. Versuchen Sie es erst, dann öffnen Sie.</p>",
 "و<code>film.ganz</code> فارغ في هذه الحالة.</p>": "und <code>film.ganz</code> ist in diesem Fall leer.</p>",
 "وأصغرُ مجالٍ (": "Und der kleinste Bereich (",
 "وإجاباتُك تبقى في متصفّحك.</span></div>": "Und Ihre Antworten bleiben in Ihrem Browser.</span></div>",
 "واثق": "Sicher",
 "والجدولةُ فوق، وزرُّ إعادة الضبط معها.</span></div>": "Die Terminplanung steht oben, und die Schaltfläche zum Zurücksetzen daneben.</span></div>",
 "والحكمُ لأذنك:</p><ul class=\"s-liste\">": "und das Urteil hat Ihr Ohr:</p><ul class=\"s-liste\">",
 "والمحطّتان تقيسهما بنفسك بمعاييرهما. ولا تدخلها جملُ التمارين ": "die beiden Stationen beurteilen Sie selbst nach ihren Kriterien. Und es gehen keine Übungssätze ein, die ",
 "وبناءُ المتعلّم لا يدخله إلّا ما اعتُمد سريريّاً. جرّب ": "und in den Lernbuild kommt nur klinisch Freigegebenes. Versuchen Sie ",
 "وتدريبٌ شفهيٌّ أو عمليّ، ومعيارُ تقييم. وثلاثةٌ من أربعةٍ فجوة.</p>": "einem mündlichen oder praktischen Training und einem Bewertungskriterium. Drei von vier sind eine Lücke.</p>",
 "وتنتظر الفيديو.</p>": "und wartet auf das Video.</p>",
 "وجملةٌ حكمتَ على نطقك فيها، ومفردةٌ نسيتَها. ولا شيءَ يُرسَل، ": "ein Satz, bei dem Sie Ihre Aussprache beurteilt haben, ein Begriff, den Sie vergessen haben. Nichts wird gesendet, ",
 "وسببُ الصواب.</p></div>": "und der Grund für die richtige Antwort.</p></div>",
 "وقائمةٌ لا فيديو مقبولٌ لها قد تكون قديمةً وقد تُعاد.</span></div>": "Eine Liste ohne angenommenes Video kann veraltet sein und neu erstellt werden.</span></div>",
 "وقتاً أكثر، ومن أيّ عنصرٍ تبدأ.</p>": "Zeit brauchen und mit welchem Element Sie anfangen.</p>",
 "وقفاتي في مواضعها ونبرتي واضحةٌ للتعليمات.": "Meine Pausen saßen richtig und meine Stimmführung war für Anweisungen klar.",
 "وقفتُ عند الفواصل ولم أَصِلِ الجملَ ببعضها.": "Ich habe an den Kommas Pausen gemacht und die Sätze nicht aneinandergehängt.",
 "وكلُّ هذا في متصفّحك.</p>": "und all das bleibt in Ihrem Browser.</p>",
 "ولا أقلّ، ويفحص ذلك <code>tools/pruefe_lehrplan.py</code>.</p>": "und nicht weniger; <code>tools/pruefe_lehrplan.py</code> prüft das.</p>",
 "ولا تتنبّأ بنتيجة امتحان المعرفة، ولا تصلح شهادةً لأحد. ": "sie sagen das Ergebnis der Kenntnisprüfung nicht voraus und sind für niemanden ein Zeugnis. ",
 "ولا تصحيحَ آليّاً للنطق هنا.</span></div>": "und eine automatische Aussprachekorrektur gibt es hier nicht.</span></div>",
 "ولا تنبّؤاً بنتيجتك.</b> والتصحيحُ الآليُّ للأسئلة وحدَها؛ ": "und keine Vorhersage Ihres Ergebnisses.</b> Automatisch bewertet werden nur die Fragen; ",
 "ولا خادم، ولا شيءَ يُرسَل. وتمسحه متى شئت من الصفحات نفسِها.</p>": "kein Server, nichts wird gesendet. Und Sie löschen es jederzeit auf denselben Seiten.</p>",
 "ولا يُوصف بأنّه صحيحٌ أو مكتمل، قبل مراجعة ممرّض/ة مؤهَّل/ة.</span></div>": "und es wird nicht als richtig oder vollständig bezeichnet, bevor eine qualifizierte Pflegefachkraft es geprüft hat.</span></div>",
 "ونوعُه يصلح. ولا يعني أنّ إنساناً شهد بأنّ المسار يحقّق المتطلَّب دلالةً — ": "und die Art passt. Es heißt nicht, dass ein Mensch bestätigt hat, dass der Pfad die Anforderung inhaltlich erfüllt — ",
 "وهذا ما يجري في الامتحان أيضاً: ينتهي الوقتُ حيث انتهى.</span></div>": "Und so ist es in der Prüfung auch: die Zeit endet, wo sie endet.</span></div>",
 "وهي مسجَّلةٌ في <code>curriculum/luecken.md</code> بانتظار مختصّ.": "Sie sind in <code>curriculum/luecken.md</code> festgehalten und warten auf eine Fachperson.",
 "ويبقى في متصفّحك ولا يُرسَل.</p>": "Es bleibt in Ihrem Browser und wird nicht gesendet.</p>",
 "ويزول بإغلاق الصفحة. ولا يُقيَّم آليّاً — قارنه أنت بالإجابة النموذجيّة.</p>": "und verschwindet beim Schließen der Seite. Es wird nicht automatisch bewertet — vergleichen Sie selbst mit der Musterantwort.</p>",
 "يحتاج إعادة": "Noch einmal",
 "يسجّل…": "nimmt auf …",
 "يسجّل… اضغط لتقف.": "Nimmt auf … zum Stoppen klicken.",
 "يمسح مواعيدَ هذه البنود وحدَها — لا إجاباتِك ولا تسجيلاتِك.": "Es löscht nur die Termine dieser Posten — nicht Ihre Antworten und nicht Ihre Aufnahmen.",
 "يومٌ واحد": "1 Tag",
 "يُقاس في: ": "Geprüft in: ",
 "١ · المقدّمة والأهداف": "1 · Einleitung und Lernziele",
 "١٠ · التوثيق التمريضيّ": "10 · Pflegedokumentation",
 "١١ · أسئلة الممتحن": "11 · Fragen der Prüfenden",
 "١٢ · أخطاء خطيرة": "12 · Schwere Fehler",
 "١٣ · حالة نقل المعرفة": "13 · Transferfall",
 "١٤ · التقييم": "14 · Bewertung",
 "١٥ · النتيجة وخطّة المراجعة": "15 · Ergebnis und Wiederholungsplan",
 "٢ · المريض والموقف": "2 · Patient und Situation",
 "٣ · الفيديو كاملاً": "3 · Das ganze Video",
 "٤ · مشاهد الفيديو": "4 · Videoszenen",
 "٥ · الحوار": "5 · Der Dialog",
 "٦ · المفردات والأساليب الثلاثة": "6 · Begriffe und die drei Register",
 "٧ · الإجراء التمريضيّ الآمن": "7 · Der sichere Pflegeablauf",
 "٨ · التواصل مع المريض": "8 · Das Gespräch mit dem Patienten",
 "٩ · تسليم الحالة بـ ISBAR": "9 · Übergabe mit ISBAR",
 "٪": "%",
 "٪ في ": "% am ",
 "٪ — <a href=\"#a-": "% — <a href=\"#a-",
 "٪)": "%)",
 "٪</b> — ": "%</b> — ",
 "٪</div>": "%</div>",
 "٪</span></div>": "%</span></div>",
 "■ أوقف": "■ Stopp",
 "🎙 تكلّم أنت": "🎙 Sie sprechen"
};
